import React from 'react';
import {
  Users,
  Shield,
  Trophy,
  Zap,
  Activity,
  BarChart3,
  Search,
  Bell,
  Settings,
  LogOut,
  Eye,
  Edit,
  Trash2,
  Check,
  X,
  ChevronLeft,
  ChevronRight,
  MoreHorizontal,
  Download,
  Upload,
  Filter,
  SortAsc,
  SortDesc,
  Plus,
  Minus,
  Home,
  User,
  Mail,
  Phone,
  Calendar,
  MapPin,
  Hash,
  Star,
  AlertTriangle,
  Info,
  CheckCircle,
  XCircle,
  Loader,
  Save,
  RefreshCw,
  Menu,
  Grid,
  List,
  EyeOff,
  Lock,
  Unlock,
  Key,
  ShieldCheck,
  UserCheck,
  UserX,
  Crown,
  Target,
  TrendingUp,
  Clock,
  Play,
  Pause,
  Square,
  SkipBack,
  SkipForward,
  Volume2,
  VolumeX,
  Wifi,
  WifiOff,
  Battery,
  BatteryCharging,
  Sun,
  Moon,
  Monitor,
  Smartphone,
  Tablet,
  Laptop,
  HardDrive,
  Database,
  Server,
  Cloud,
  Globe,
  Map,
  Navigation,
  Compass,
  Flag,
  Award,
  Medal,
  Gift,
  Heart,
  ThumbsUp,
  ThumbsDown,
  MessageCircle,
  MessageSquare,
  Send,
  Inbox,
  Archive,
  Trash,
  Folder,
  FolderOpen,
  File,
  FileText,
  Image,
  Video,
  Music,
  Headphones,
  Mic,
  MicOff,
  Camera,
  CameraOff,
  Printer,
  Paperclip,
  Link,
  ExternalLink,
  Share,
  Bookmark,
  Tag,
  Hash as HashIcon,
  AtSign,
  DollarSign,
  Percent,
  PieChart,
  BarChart,
  LineChart,
  TrendingDown
} from 'lucide-react';

const Icon = ({ name, size = 16, className = '', ...props }) => {
  const iconMap = {
    users: Users,
    shield: Shield,
    trophy: Trophy,
    zap: Zap,
    activity: Activity,
    barChart3: BarChart3,
    search: Search,
    bell: Bell,
    settings: Settings,
    logOut: LogOut,
    eye: Eye,
    edit: Edit,
    trash2: Trash2,
    check: Check,
    x: X,
    chevronLeft: ChevronLeft,
    chevronRight: ChevronRight,
    moreHorizontal: MoreHorizontal,
    download: Download,
    upload: Upload,
    filter: Filter,
    sortAsc: SortAsc,
    sortDesc: SortDesc,
    plus: Plus,
    minus: Minus,
    home: Home,
    user: User,
    mail: Mail,
    phone: Phone,
    calendar: Calendar,
    mapPin: MapPin,
    hash: Hash,
    star: Star,
    alertTriangle: AlertTriangle,
    info: Info,
    checkCircle: CheckCircle,
    xCircle: XCircle,
    loader: Loader,
    save: Save,
    refreshCw: RefreshCw,
    menu: Menu,
    grid: Grid,
    list: List,
    eyeOff: EyeOff,
    lock: Lock,
    unlock: Unlock,
    key: Key,
    shieldCheck: ShieldCheck,
    userCheck: UserCheck,
    userX: UserX,
    crown: Crown,
    target: Target,
    trendingUp: TrendingUp,
    clock: Clock,
    play: Play,
    pause: Pause,
    square: Square,
    skipBack: SkipBack,
    skipForward: SkipForward,
    volume2: Volume2,
    volumeX: VolumeX,
    wifi: Wifi,
    wifiOff: WifiOff,
    battery: Battery,
    batteryCharging: BatteryCharging,
    sun: Sun,
    moon: Moon,
    monitor: Monitor,
    smartphone: Smartphone,
    tablet: Tablet,
    laptop: Laptop,
    hardDrive: HardDrive,
    database: Database,
    server: Server,
    cloud: Cloud,
    globe: Globe,
    map: Map,
    navigation: Navigation,
    compass: Compass,
    flag: Flag,
    award: Award,
    medal: Medal,
    gift: Gift,
    heart: Heart,
    thumbsUp: ThumbsUp,
    thumbsDown: ThumbsDown,
    messageCircle: MessageCircle,
    messageSquare: MessageSquare,
    send: Send,
    inbox: Inbox,
    archive: Archive,
    trash: Trash,
    folder: Folder,
    folderOpen: FolderOpen,
    file: File,
    fileText: FileText,
    image: Image,
    video: Video,
    music: Music,
    headphones: Headphones,
    mic: Mic,
    micOff: MicOff,
    camera: Camera,
    cameraOff: CameraOff,
    printer: Printer,
    paperclip: Paperclip,
    link: Link,
    externalLink: ExternalLink,
    share: Share,
    bookmark: Bookmark,
    tag: Tag,
    hashIcon: HashIcon,
    atSign: AtSign,
    dollarSign: DollarSign,
    percent: Percent,
    pieChart: PieChart,
    barChart: BarChart,
    lineChart: LineChart,
    trendingDown: TrendingDown
  };

  const IconComponent = iconMap[name];

  if (!IconComponent) {
    console.warn(`Icon "${name}" not found`);
    return null;
  }

  return (
    <IconComponent
      size={size}
      className={className}
      {...props}
    />
  );
};

export default Icon;
