name: Flutter CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - name: Get dependencies
        working-directory: frontend
        run: flutter pub get
      - name: Analyze
        working-directory: frontend
        run: flutter analyze
      - name: Test
        working-directory: frontend
        run: flutter test --machine --coverage


